var express = require('express');
var solc = require('solc');
var abi = require('solc/abi')
var router = express.Router();

/* GET users listing. */
router.post('/compile', function(req, res, next) {
  var compiled = solc.compile({sources: req.body}, 1);

  res.json(compiled)
});

/**
  Updates the ABI generated by an older version of Solidity to the latest version.

  Body Input: {
    input_ABI: [ ... ],
    ABI_version: "0.3.6"
  }

  Returns: {
    updated_ABI: [ ... ]
  }

*/
router.post('/update_abi', function(req, res, next) {
  var result = {};

  var input_ABI = req.body.input_ABI;
  var ABI_version = req.body.ABI_version
  var output_ABI = abi.update(ABI_version, input_ABI)

  result.updated_ABI = output_ABI;

  res.json(result)
});

module.exports = router;
